Repository wavelog/wavelog, pull requests merged in 2024-06, with the labels that each got.

#464 Fixes showing other stations QSL-Requests
  application/models/Qslprint_model.php
Labels: security

#473 [QRZ] Fix QSL downloads
  application/controllers/Qrz.php
  application/models/Logbook_model.php
Labels: bug

#474 [OQRS] Fix saving Station Locations
  application/models/Stations.php
Labels: bug

#478 Translations update from Weblate
  application/locale/cs_CZ/LC_MESSAGES/messages.po
  application/locale/de_DE/LC_MESSAGES/messages.po
Labels: language

#492 "Operator Dialog" for Amateur Radio Club's and Special Callsign Activities
  application/config/config.sample.php
  application/controllers/Operator.php
  application/controllers/User.php
  application/views/interface_assets/footer.php
  application/views/interface_assets/header.php
  application/views/operator/index.php
  assets/js/sections/operator.js
  install/config/config.php
Labels: enhancement
