Repository wavelog/wavelog, pull requests merged in 2024-07, with the labels that each got.

#517 [QSO] sanitize some input data
  assets/js/sections/qso.js
Labels: bug

#526 [QSO] Skip Radio Cookie
  application/controllers/Qso.php
  application/models/User_model.php
Labels: bug

#540 Fix lang selection in User Edit (other user as admin)
  application/views/user/edit.php
Labels: bug

#543 [QRZ & HamQTH] Fix Callbook Lookup
  application/controllers/Logbook.php
  application/libraries/Hamqth.php
  application/libraries/Qrz.php
  application/models/Logbook_model.php
Labels: bug

#555 SecFix: Some eqsl-functions could even be called without authentication
  application/controllers/Eqsl.php
Labels: security

#573 Handle propagation modes not suppored by LoTW (i.e. RPT & INTERNET)
  application/config/lotw.php
  application/config/migration.php
  application/controllers/Lotw.php
  application/controllers/Qso.php
  application/locale/de_DE/LC_MESSAGES/messages.po
  application/migrations/209_unmark_unsupported_lotw_uploads.php
  application/models/Logbook_model.php
  application/views/interface_assets/footer.php
  application/views/oqrs/qsolist.php
  application/views/qslprint/qsolist.php
  application/views/qso/edit_ajax.php
  application/views/search/search_result_ajax.php
  application/views/view_log/partial/log_ajax.php
  assets/css/general.css
  assets/js/sections/common.js
  src/QSLManager/QSO.php
Labels: enhancement

#572 Label mark
  application/models/Qslprint_model.php
  application/views/labels/index.php
  application/views/labels/startatform.php
  application/views/logbookadvanced/startatform.php
  assets/js/sections/labels.js
  assets/js/sections/logbookadvanced.js
Labels: enhancement

#579 Added VUCC to accumulated-stats
  application/models/Accumulate_model.php
  application/views/accumulate/index.php
  assets/js/sections/accumulatedstatistics.js
Labels: enhancement

#616 [OQRS] iFrame Widget für Wavelog OQRS
  application/controllers/Oqrs.php
  application/controllers/Widgets.php
  application/libraries/OptionsLib.php
  application/views/oqrs/index.php
  application/views/widgets/oqrs.php
  assets/css/general.css
  assets/js/sections/oqrs.js
Labels: enhancement, frontend

#612 handle special chars in passwords
  application/models/User_model.php
Labels: bug

#603 [INSTALLER] Next generation of the Wavelog Installer
  .gitignore
  application/controllers/Migrate.php
  application/controllers/Update.php
  application/controllers/User.php
  application/views/debug/index.php
  application/views/interface_assets/footer.php
  assets/js/country-flag-emoji-polyfill.js
  install/ajax.php
  install/assets/css/installer.css
  install/assets/install.sql
  install/config/config.php
  install/includes/core/core_class.php
  install/includes/core/database_class.php
  install/includes/gettext/gettext.php
  install/includes/gettext/gettext_conf.php
  install/includes/install_config/install_config.php
  install/includes/install_config/install_lib.php
  install/includes/interface_assets/footer.php
  install/includes/interface_assets/header.php
  install/includes/interface_assets/triggers.php
  install/index.php
  install/nginx.php
  install/run.php
  system/libraries/Migration.php
Labels: enhancement

#660 Add curl to installer required modules
  install/includes/install_config/install_config.php
  install/includes/install_config/install_lib.php
  install/index.php
Labels: bug

#643 DXCC Dropdown
  application/views/logbookadvanced/index.php
  assets/css/cosmo/overrides.css
  assets/css/cosmo_wide/overrides.css
  assets/css/cyborg/overrides.css
  assets/css/cyborg_wide/overrides.css
  assets/css/darkly/overrides.css
  assets/css/darkly_wide/overrides.css
  assets/css/default/overrides.css
  assets/css/default_wide/overrides.css
  assets/css/general.css
  assets/css/superhero/overrides.css
  assets/css/superhero_wide/overrides.css
  assets/js/sections/logbookadvanced.js
Labels: frontend

#667 VUCC grids are not plotted correctly on the dashboard map
  application/models/Logbook_model.php
Labels: bug

#670 Apply user defined units to distance plots on map
  assets/js/leaflet/geocoding.js
Labels: bug
