Repository wavelog/wavelog, pull requests merged in 2024-05, with the labels that each got.

#306 [CRON] Cron Manager
  application/config/migration.php
  application/controllers/Clublog.php
  application/controllers/Cron.php
  application/controllers/Debug.php
  application/controllers/Eqsl.php
  application/controllers/Hrdlog.php
  application/controllers/Lotw.php
  application/controllers/Qrz.php
  application/controllers/Update.php
  application/libraries/CronExpression.php
  application/migrations/196_cron_table.php
  application/models/Cron_model.php
  application/views/cron/edit.php
  application/views/cron/index.php
  application/views/debug/index.php
  application/views/interface_assets/footer.php
  application/views/interface_assets/header.php
  assets/js/cronstrue.min.js
  assets/js/sections/cron.js
Labels: enhancement, major impact

#330 Menu sorted
  application/language/bulgarian/menu_lang.php
  application/language/chinese_simplified/menu_lang.php
  application/language/czech/menu_lang.php
  application/language/dutch/menu_lang.php
  application/language/english/menu_lang.php
  application/language/finnish/menu_lang.php
  application/language/french/menu_lang.php
  application/language/german/menu_lang.php
  application/language/greek/menu_lang.php
  application/language/italian/menu_lang.php
  application/language/polish/menu_lang.php
  application/language/russian/menu_lang.php
  application/language/spanish/menu_lang.php
  application/language/swedish/menu_lang.php
  application/language/turkish/menu_lang.php
  application/views/interface_assets/footer.php
  application/views/interface_assets/header.php
  assets/css/general.css
  assets/fonts/TwemojiCountryFlags/LICENCE.md
  assets/fonts/TwemojiCountryFlags/TwemojiCountryFlags.woff2
  assets/js/country-flag-emoji-polyfill.js
Labels: frontend

#334 Fix QSL arrows
  assets/css/general.css
Labels: frontend

#322 [SFLE] Adding Support for more Frequencies and Modes
  application/controllers/Simplefle.php
  application/models/Bands.php
  application/views/simplefle/index.php
  assets/js/sections/simplefle.js
Labels: enhancement

#293 some ideas for the Docker support
  Dockerfile
Labels: Wait for other PR

#341 Option to show UTC time in header menu
  application/controllers/User.php
  application/views/interface_assets/header.php
  application/views/user/edit.php
  assets/js/sections/common.js
Labels: frontend

#344 [GRIDMAP] Create a Gridmap based on Propagation Mode
  application/controllers/Activated_gridmap.php
  application/controllers/Awards.php
  application/controllers/Gridmap.php
  application/models/Activated_gridmap_model.php
  application/models/Gridmap_model.php
  application/models/Logbook_model.php
  application/views/gridmap/index.php
  assets/js/sections/gridmap.js
Labels: enhancement

#338 [C to M] Part 1 - Update_Model
  application/controllers/Update.php
  application/libraries/Paths.php
  application/models/Update_model.php
Labels: major impact

#355 Contestcalendar
  application/controllers/Contestcalendar.php
  application/views/contestcalendar/index.php
Labels: enhancement, frontend

#340 Cron special expressions (@...)
  application/controllers/Cron.php
  application/libraries/CronExpression.php
  application/views/cron/index.php
  assets/js/cronstrue.min.js
Labels: enhancement

#405 Activators Refactoring
  application/controllers/Activators.php
  application/models/Activators_model.php
  application/models/Logbook_model.php
  application/views/activators/details.php
  application/views/activators/index.php
  application/views/interface_assets/footer.php
  assets/js/sections/activators.js
Labels: frontend

#431 [QSO] Only overwrite Frequency if no Radio is selected
  assets/js/sections/qso.js
Labels: bug

#435 Improve chinese_simplified localization
  application/language/chinese_simplified/account_lang.php
  application/language/chinese_simplified/adif_lang.php
  application/language/chinese_simplified/admin_lang.php
  application/language/chinese_simplified/awards_lang.php
  application/language/chinese_simplified/export_lang.php
  application/language/chinese_simplified/filter_lang.php
  application/language/chinese_simplified/general_words_lang.php
  application/language/chinese_simplified/lotw_lang.php
  application/language/chinese_simplified/menu_lang.php
  application/language/chinese_simplified/options_lang.php
  application/language/chinese_simplified/qslcard_lang.php
  application/language/chinese_simplified/qso_lang.php
  application/language/chinese_simplified/station_lang.php
Labels: language
