Repository wavelog/wavelog, pull requests merged in 2024-09, with the labels that each got.

#852 Insert Warning if no station is linked
  application/controllers/Dashboard.php
  application/views/dashboard/index.php
Labels: enhancement, frontend

#851 Adds eQSL-Checkbox to importer (import as already sent)
  application/controllers/Adif.php
  application/controllers/Api.php
  application/models/Logbook_model.php
  application/views/adif/import.php
Labels: enhancement, awards

#859 Add input/edit boxes for antenna azimuth / elevation
  application/controllers/Qso.php
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
Labels: enhancement

#861 Function to show distance records per SAT
  application/controllers/Distancerecords.php
  application/models/Distancerecords_model.php
  application/models/Logbook_model.php
  application/views/distancerecords/details.php
  application/views/distancerecords/index.php
  assets/js/sections/distancerecords.js
Labels: enhancement

#862 Put az/el boxes to the sat pane and handle empty / 0 values
  application/models/Logbook_model.php
  application/views/qso/index.php
  assets/js/sections/qso.js
Labels: bug

#868 Add gridsquare hint to distance column
  application/views/view_log/partial/log_ajax.php
Labels: enhancement, frontend

#867 Just give empty result on frequency being 0
  application/libraries/Frequency.php
  application/views/view_log/qso.php
Labels: frontend

#870 show the "To Radio" string in the upper right corner
  application/controllers/Labels.php
  src/Label/vendor/malios/php-to-ascii-table/src/Builder.php
Labels: enhancement

#875 Make the Header Logo link on OQRS page go back to public slug page
  application/controllers/Oqrs.php
  application/controllers/Visitor.php
  application/models/Oqrs_model.php
  application/models/Publicsearch.php
  application/views/visitor/layout/footer.php
  application/views/visitor/layout/header.php
Labels: enhancement

#876 Show open and total number of OQRS requests
  application/models/Oqrs_model.php
  application/views/interface_assets/header.php
Labels: enhancement, frontend

#850 Fix user login / edit set cookies
  application/controllers/User.php
Labels: bug

#889 Refactor sattimers
  application/views/sattimers/index.php
Labels: enhancement

#887 [OQRS] Security and some bugfixes
  application/controllers/Oqrs.php
  application/models/Oqrs_model.php
  assets/js/sections/oqrs.js
Labels: security

#895 unset freq_in_mhz(_rx) before each QSO
  application/views/lotw_views/adif_views/adif_export.php
Labels: bug

#898 fix public map
  application/views/visitor/layout/footer.php
Labels: bug

#894 Award binding
  application/libraries/Genfunctions.php
  application/models/Cq.php
  application/models/Dok.php
  application/models/Dxcc.php
  application/models/Helvetia_model.php
  application/models/Iota.php
  application/models/Itu.php
  application/models/Jcc_model.php
  application/models/Rac.php
  application/models/Wab.php
  application/models/Wac.php
  application/models/Waja.php
  application/models/Was.php
Labels: security

#906 Fix Contest Bulk-Edit
  assets/js/sections/logbookadvanced_edit.js
Labels: bug

#907 Qrz state modified
  application/views/view_log/partial/log_ajax.php
  assets/css/general.css
Labels: enhancement

#909 Link GMA page
  application/views/view_log/qso.php
Labels: enhancement

#905 [CONTESTING] Fix some issues in contesting
  application/controllers/Contesting.php
  application/models/Contesting_model.php
  application/views/contesting/index.php
  application/views/interface_assets/footer.php
  assets/js/sections/contesting.js
Labels: bug

#935 Lookup ITU zone from DXCC if callbook results are empty
  application/models/Logbook_model.php
Labels: enhancement

#934 Notes are getting exported
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
Labels: bug

#939 Mark QRZ-QSOs as Invalid when specific Error at qrz while uploading
  application/controllers/Qrz.php
  application/models/Logbook_model.php
  application/views/view_log/partial/log_ajax.php
  assets/css/general.css
Labels: enhancement

#946 Fix some minor eQSL-Issues where values aren't set
  application/controllers/Eqsl.php
  application/libraries/EqslImporter.php
Labels: bug

#947 Set BandRX to empty (not null) if not derivateable (as last defence)
  application/models/Logbook_model.php
Labels: bug

#950 Fixes issue, where browser sends an empty string instead of null
  application/models/Logbook_model.php
Labels: bug

#954 [Advanced Logbook] set qrz to modified when update from callbook or batch edit
  application/models/Logbookadvanced_model.php
  application/views/logbookadvanced/index.php
Labels: bug

#957 Keep eQSL incoming QSL arrows green on selection
  assets/css/general.css
Labels: enhancement

#960 Order LoTW certs by callsign
  application/models/Lotw_model.php
Labels: frontend

#963 fix an issue with station ids
  application/models/Logbook_model.php
Labels: bug

#967 i forgot about translation :D
  application/views/debug/index.php
Labels: language

#961 [ADIF] Catch some more ADIF errors
  application/models/Logbook_model.php
Labels: bug

#968 Ignore invalid DXCC for qrz.com uploads
  application/controllers/Qrz.php
  src/QSLManager/QSO.php
Labels: enhancement

#975 Datatable Language
  assets/json/datatables_languages/bs.json
  assets/json/datatables_languages/sq.json
  assets/json/datatables_languages/sr.json
Labels: enhancement

#973 Fix number of US counties
  application/controllers/Lookup.php
Labels: bug

#943 fixes buggy modal dialog
  assets/js/leaflet/geocoding.js
  assets/js/sections/common.js
  assets/js/sections/distancerecords.js
  assets/js/sections/gridmap.js
Labels: bug

#985 Fixes a security-issue with the INTERNAL lookup-API
  application/controllers/Api.php
  application/models/Logbook_model.php
Labels: security

#990 Lightbox for Callbook Image
  assets/js/sections/qso.js
Labels: enhancement

#993 There was a typo at the Clublog-QSO-Upload-Status
  application/models/Logbookadvanced_model.php
Labels: bug

#991 QSO logging tabindex
  application/views/qso/index.php
Labels: bug, frontend

#988 QRZ state modified on quick buttons
  application/models/Logbook_model.php
  application/models/Logbookadvanced_model.php
  application/views/view_log/partial/log_ajax.php
  assets/js/sections/common.js
Labels: bug

#1019 Change Gridmaster Award text for non-US DXCCs
  application/views/awards/gridmaster/index.php
Labels: enhancement

#1018 Fix empty eQSL received date
  application/views/eqslcard/index.php
Labels: bug
