Repository wavelog/wavelog, pull requests merged in 2024-04, with the labels that each got.

#283 Debug info
  application/views/debug/index.php
Labels: enhancement

#299 Fix broken QSO-Detail-Links
  assets/js/sections/cqmap.js
  assets/js/sections/helvetiamap.js
  assets/js/sections/racmap.js
  assets/js/sections/wajamap.js
  assets/js/sections/wasmap.js
Labels: bug

#321 JCC map function
  application/controllers/Awards.php
  application/language/bulgarian/awards_lang.php
  application/language/chinese_simplified/awards_lang.php
  application/language/czech/awards_lang.php
  application/language/dutch/awards_lang.php
  application/language/english/awards_lang.php
  application/language/finnish/awards_lang.php
  application/language/french/awards_lang.php
  application/language/german/awards_lang.php
  application/language/greek/awards_lang.php
  application/language/italian/awards_lang.php
  application/language/polish/awards_lang.php
  application/language/russian/awards_lang.php
  application/language/spanish/awards_lang.php
  application/language/swedish/awards_lang.php
  application/language/turkish/awards_lang.php
  application/models/Jcc_model.php
  application/views/awards/jcc/index.php
  assets/js/sections/jccmap.js
Labels: awards
