Repository wavelog/wavelog, pull requests merged in 2024-08, with the labels that each got.

#703 Fixing XSS Vulnerability
  application/controllers/Contesting.php
  application/controllers/Lookup.php
  application/controllers/Qso.php
  application/views/contesting/index.php
  application/views/interface_assets/footer.php
  application/views/qso/index.php
Labels: security

#705 Fix calculation of distance if wked from same-grid or other errors
  application/libraries/Qra.php
Labels: bug

#713 Fixes a bug where $band wasn't set
  application/views/gridmap/index.php
Labels: bug

#715 [INSTALLER] Fulltext searchable DXCC dropdown in Installer
  install/assets/css/installer.css
  install/includes/interface_assets/footer.php
  install/index.php
Labels: enhancement, installer

#720 [SFLE] RST was saved swapped around
  assets/js/sections/simplefle.js
Labels: bug

#700 Default Radio
  application/controllers/Contesting.php
  application/controllers/Qso.php
  application/controllers/Radio.php
  application/models/Cat.php
  application/models/User_model.php
  application/views/contesting/index.php
  application/views/interface_assets/footer.php
  application/views/qso/index.php
  application/views/radio/index.php
  assets/js/sections/radio.js
Labels: enhancement, frontend

#724 Sat stuff
  application/controllers/Satellite.php
  application/views/satellite/pass.php
  application/views/satellite/passtable.php
Labels: enhancement

#736 Bindings
  application/controllers/Logbook.php
Labels: security

#737 Bindings
  application/controllers/Accumulated.php
  application/models/Accumulate_model.php
  application/models/Logbook_model.php
Labels: security

#742 Cookies Fix
  application/controllers/User.php
  application/hooks/gettext/Gettext.php
  application/views/debug/index.php
Labels: bug

#744 xss cleaning in qso controller
  application/controllers/Lookup.php
  application/controllers/Qso.php
  application/controllers/Search.php
Labels: security

#738 Preventing SQL-Injection
  application/models/Logbook_model.php
Labels: security

#750 notes xss cleaning
  application/controllers/Backup.php
  application/controllers/Notes.php
  application/models/Note.php
Labels: security

#752 Prevent SQL Injections in Helvetia Model
  application/models/Helvetia_model.php
Labels: security

#748 Searchable DXCC Dropdowns
  application/libraries/Subdivisions.php
  application/views/interface_assets/footer.php
  application/views/qso/index.php
  application/views/station_profile/create.php
  application/views/station_profile/edit.php
  assets/css/general.css
  assets/js/sections/qso.js
  assets/js/sections/station_locations.js
Labels: frontend

#758 [GETTEXT] HTML encoding
  application/hooks/gettext/vendor/php-gettext/gettext.php
  application/views/adif/import.php
  application/views/debug/index.php
  application/views/distances/index.php
  application/views/interface_assets/footer.php
  application/views/simplefle/index.php
  application/views/simplefle/syntax_help.php
  application/views/themes/index.php
  application/views/user/login.php
Labels: security, language

#761 Dashboard warnings
  application/controllers/Accumulated.php
  application/controllers/Activators.php
  application/controllers/Activatorsmap.php
  application/controllers/Adif.php
  application/controllers/Awards.php
  application/controllers/Backup.php
  application/controllers/Band.php
  application/controllers/Bandmap.php
  application/controllers/Cabrillo.php
  application/controllers/Calltester.php
  application/controllers/Cfdexport.php
  application/controllers/Components.php
  application/controllers/Contestcalendar.php
  application/controllers/Contesting.php
  application/controllers/Cron.php
  application/controllers/Csv.php
  application/controllers/Dashboard.php
  application/controllers/Dayswithqso.php
  application/controllers/Debug.php
  application/controllers/Distances.php
  application/controllers/Dxatlas.php
  application/controllers/Dxcalendar.php
  application/controllers/Dxcluster.php
  application/controllers/Eqsl.php
  application/controllers/Hamsat.php
  application/controllers/Kmlexport.php
  application/controllers/Labels.php
  application/controllers/Logbookadvanced.php
  application/controllers/Lookup.php
  application/controllers/Lotw.php
  application/controllers/Mode.php
  application/controllers/Notes.php
  application/controllers/Options.php
  application/controllers/Oqrs.php
  application/controllers/Qrbcalc.php
  application/controllers/Qrz.php
  application/controllers/Qsl.php
  application/controllers/Qslprint.php
  application/controllers/Qso.php
  application/controllers/Radio.php
  application/controllers/Satellite.php
  application/controllers/Sattimers.php
  application/controllers/Search.php
  application/controllers/Simplefle.php
  application/controllers/Station.php
  application/controllers/Stationsetup.php
  application/controllers/Themes.php
  application/controllers/Timeline.php
  application/controllers/Timeplotter.php
  application/controllers/Update.php
  application/controllers/User.php
  application/controllers/User_options.php
  application/views/dashboard/index.php
Labels: frontend

#759 Translations update from Weblate
  application/locale/bg_BG/LC_MESSAGES/messages.po
  application/locale/bs/LC_MESSAGES/messages.po
  application/locale/cnr/LC_MESSAGES/messages.po
  application/locale/cs_CZ/LC_MESSAGES/messages.po
  application/locale/de_DE/LC_MESSAGES/messages.po
  application/locale/el_GR/LC_MESSAGES/messages.po
  application/locale/es_ES/LC_MESSAGES/messages.po
  application/locale/fi_FI/LC_MESSAGES/messages.po
  application/locale/fr_FR/LC_MESSAGES/messages.po
  application/locale/hr/LC_MESSAGES/messages.po
  application/locale/it_IT/LC_MESSAGES/messages.po
  application/locale/nl_NL/LC_MESSAGES/messages.po
  application/locale/pl_PL/LC_MESSAGES/messages.po
  application/locale/pt_PT/LC_MESSAGES/messages.po
  application/locale/ru_RU/LC_MESSAGES/messages.po
  application/locale/sq/LC_MESSAGES/messages.po
  application/locale/sr/LC_MESSAGES/messages.po
  application/locale/sv_SE/LC_MESSAGES/messages.po
  application/locale/tr_TR/LC_MESSAGES/messages.po
  application/locale/zh_CN/LC_MESSAGES/messages.po
Labels: hold

#767 Use grid of active station location for distance calculations
  application/controllers/Logbook.php
  application/controllers/Update.php
  application/models/Logbook_model.php
  application/views/update/index.php
Labels: bug

#762 Impersonate
  application/config/config.sample.php
  application/controllers/User.php
  application/models/User_model.php
  application/views/user/index.php
  install/config/config.php
Labels: enhancement

#778 [LoTW] Fix flash messages and catch the case if a user tries to upload a 'key-only' file
  application/controllers/Lotw.php
  application/views/lotw_views/index.php
Labels: bug

#765 DXCC Multiselect - Scroll on Mobile does not work
  application/views/interface_assets/footer.php
  application/views/station_profile/create.php
  application/views/station_profile/edit.php
  assets/css/general.css
  assets/js/sections/logbookadvanced.js
  assets/js/sections/qso.js
  assets/js/sections/station_locations.js
  install/assets/css/installer.css
Labels: bug, frontend

#775 Refactor QRB language and improve UI
  application/controllers/Qrbcalc.php
  application/views/interface_assets/footer.php
  application/views/qrbcalc/index.php
  assets/js/sections/common.js
Labels: enhancement, frontend, language

#785 [CRON] Allow insecure self-signed certificates with config switch
  application/config/config.sample.php
  application/controllers/Cron.php
  application/views/cron/index.php
  install/config/config.php
Labels: enhancement

#783 Stop empty or zero freq from breaking LoTW confirmations
  application/views/lotw_views/adif_views/adif_export.php
Labels: bug

#787 Fixing Winkey sending
  application/views/qso/index.php
  assets/js/winkey.js
Labels: bug

#795 Create a helper to read in a optional local_url to bypass the need to…
  application/controllers/Cron.php
  system/core/Config.php
  system/helpers/url_helper.php
Labels: enhancement

#809 Update buttons locked and with spinner class
  application/views/interface_assets/footer.php
  application/views/update/index.php
  assets/js/htmx.min.js
Labels: enhancement

#806 Allow AMSAT status page upload for QSOs logged via API
  application/models/Logbook_model.php
  application/models/User_model.php
Labels: enhancement

#812 [Contesting] Added Exchangetype "Serial + Grid + Exchange"
  application/models/Contesting_model.php
  application/models/Logbook_model.php
  application/views/contesting/index.php
  assets/js/sections/contesting.js
Labels: enhancement

#797 Add EDI export for contests in REG1TEST format
  application/controllers/Reg1test.php
  application/libraries/Qra.php
  application/libraries/Reg1testformat.php
  application/models/Contesting_model.php
  application/views/interface_assets/header.php
  application/views/reg1test/export.php
  application/views/reg1test/index.php
  assets/js/sections/reg1test.js
Labels: enhancement

#825 Lookup CQ zones in qrz/hamqth
  application/controllers/Logbook.php
  application/libraries/Hamqth.php
  application/libraries/Qrz.php
  application/models/Logbook_model.php
  assets/js/sections/qso.js
Labels: enhancement

#824 ITU Single Lookups
  application/models/Logbookadvanced_model.php
  assets/js/sections/common.js
Labels: enhancement

#826 Prevent QRA lib being loaded over and over again (and spilling debug log)
  application/controllers/Qso.php
  application/views/qso/components/previous_contacts.php
Labels: bug

#828 [CONTEST] Store Settings in Database
  application/config/migration.php
  application/controllers/Contesting.php
  application/migrations/215_add_contest_settings.php
  application/models/Contesting_model.php
  application/models/Logbook_model.php
  application/views/contesting/index.php
  application/views/qso/index.php
  assets/js/sections/contesting.js
Labels: enhancement

#830 Impersonate maintenance
  application/controllers/User.php
  application/models/User_model.php
  application/views/user/index.php
Labels: enhancement

#840 Add page with distance records per SAT
  application/controllers/Distancerecords.php
  application/models/Distancerecords_model.php
  application/views/distancerecords/index.php
  application/views/interface_assets/footer.php
  application/views/interface_assets/header.php
Labels: enhancement
