Repository wavelog/wavelog, pull requests merged in 2024-02, with the labels that each got.

#89 [QSO] Moved QRG to first tab
  application/views/qso/index.php
Labels: frontend

#95 Show IOTA/SOTA ref on station location tab
  application/views/view_log/qso.php
Labels: enhancement

#100 Make consequent use of SIG-References from station_profile
  application/controllers/Logbook.php
  application/models/Logbook_model.php
  application/views/view_log/qso.php
Labels: bug, enhancement

#70 [USER DATA] centralise directory for user data (eqsl, qsl)
  application/config/autoload.php
  application/config/config.sample.php
  application/controllers/Eqsl.php
  application/controllers/Qsl.php
  application/libraries/Paths.php
  application/models/Eqsl_images.php
  application/models/Qsl_model.php
  application/views/interface_assets/footer.php
  application/views/logbookadvanced/qslcarousel.php
  application/views/qslcard/qslcarousel.php
  application/views/view_log/qso.php
  install/config/config.php
Labels: enhancement

#114 Removed dangerous functions where User can accidently shift profiles
  application/controllers/Maintenance.php
  application/controllers/Station.php
  application/models/Api_model.php
  application/models/Note.php
  application/models/Stations.php
  application/views/station_profile/index.php
  application/views/stations/index.php
Labels: security

#110 Header refactoring
  application/language/bulgarian/menu_lang.php
  application/language/chinese_simplified/menu_lang.php
  application/language/czech/menu_lang.php
  application/language/dutch/menu_lang.php
  application/language/english/menu_lang.php
  application/language/finnish/menu_lang.php
  application/language/french/menu_lang.php
  application/language/german/menu_lang.php
  application/language/greek/menu_lang.php
  application/language/italian/menu_lang.php
  application/language/polish/menu_lang.php
  application/language/russian/menu_lang.php
  application/language/spanish/menu_lang.php
  application/language/swedish/menu_lang.php
  application/language/turkish/menu_lang.php
  application/views/interface_assets/header.php
  assets/css/cyborg/overrides.css
  assets/css/cyborg_wide/overrides.css
  assets/css/darkly/overrides.css
  assets/css/darkly_wide/overrides.css
  assets/css/general.css
  assets/css/superhero/overrides.css
  assets/css/superhero_wide/overrides.css
Labels: frontend

#133 Fix space in adif
  application/controllers/Adif.php
  application/models/Logbook_model.php
  application/views/adif/import.php
  assets/js/sections/adif.js
Labels: bug

#145 [QSO View/Edit] States from Database
  application/controllers/Lookup.php
  application/controllers/Qso.php
  application/libraries/Subdivisions.php
  application/models/Logbook_model.php
  application/views/interface_assets/footer.php
  application/views/lookup/index.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  application/views/station_profile/create.php
  application/views/station_profile/edit.php
  assets/css/cyborg/overrides.css
  assets/css/cyborg_wide/overrides.css
  assets/css/darkly/overrides.css
  assets/css/darkly_wide/overrides.css
  assets/css/superhero/overrides.css
  assets/css/superhero_wide/overrides.css
  assets/js/sections/common.js
  assets/js/sections/qso.js
  assets/js/sections/station_locations.js
Labels: enhancement, major impact

#146 H26 award
  application/config/migration.php
  application/controllers/Awards.php
  application/controllers/Band.php
  application/language/bulgarian/awards_lang.php
  application/language/bulgarian/menu_lang.php
  application/language/chinese_simplified/awards_lang.php
  application/language/chinese_simplified/menu_lang.php
  application/language/czech/awards_lang.php
  application/language/czech/menu_lang.php
  application/language/dutch/awards_lang.php
  application/language/dutch/menu_lang.php
  application/language/english/awards_lang.php
  application/language/english/menu_lang.php
  application/language/finnish/awards_lang.php
  application/language/finnish/menu_lang.php
  application/language/french/awards_lang.php
  application/language/french/menu_lang.php
  application/language/german/awards_lang.php
  application/language/german/menu_lang.php
  application/language/greek/awards_lang.php
  application/language/greek/menu_lang.php
  application/language/italian/awards_lang.php
  application/language/italian/menu_lang.php
  application/language/polish/awards_lang.php
  application/language/polish/menu_lang.php
  application/language/russian/awards_lang.php
  application/language/russian/menu_lang.php
  application/language/spanish/awards_lang.php
  application/language/spanish/menu_lang.php
  application/language/swedish/awards_lang.php
  application/language/swedish/menu_lang.php
  application/language/turkish/awards_lang.php
  application/language/turkish/menu_lang.php
  application/migrations/181_add_helvetia_bandxuser.php
  application/models/Bands.php
  application/models/Helvetia_model.php
  application/models/Logbook_model.php
  application/models/User_model.php
  application/views/awards/helvetia/index.php
  application/views/bands/index.php
  application/views/interface_assets/footer.php
  application/views/interface_assets/header.php
  assets/js/sections/bands.js
  assets/js/sections/helvetiamap.js
  assets/js/sections/helvetiamap_geojson.js
Labels: awards

#168 fix adif county
  application/libraries/AdifHelper.php
  application/models/Stations.php
Labels: bug

#170 fix lotw cert upload flashdata messages
  application/controllers/Lotw.php
Labels: bug
