Repository wavelog/wavelog, pull requests merged in 2024-10, with the labels that each got.

#1028 Use station_ids for import_check
  application/controllers/Qrz.php
  application/models/Logbook_model.php
Labels: bug, security

#1029 Added exceptionhandling for QSOs with no Call
  application/controllers/Lotw.php
  application/controllers/Qrz.php
  application/libraries/Adif_parser.php
  application/libraries/EqslImporter.php
  application/models/Logbook_model.php
Labels: bug

#1017 Added a new api: /api/private_lookup
  application/controllers/Api.php
  application/models/Logbook_model.php
Labels: enhancement, API

#1031 Correct VFDB Link (missing dot for sub domain)
  src/QSLManager/QSO.php
Labels: bug

#1035 Lotw cert hint
  application/views/lotw_views/upload_cert.php
Labels: frontend

#1027 Show last sent date in case of modified for qrz
  application/views/view_log/partial/log_ajax.php
  src/QSLManager/QSO.php
Labels: bug, frontend

#1038 Handle UTF8-Chars for eQSL-Credentials at upload correct
  application/models/Eqslmethods_model.php
Labels: bug

#1039 [CABRILLO] Fixed a small bug and added some more optional fields
  application/controllers/Cabrillo.php
  application/libraries/Cabrilloformat.php
  application/views/cabrillo/export.php
  application/views/cabrillo/index.php
  assets/js/sections/cabrillo.js
Labels: bug, enhancement

#978 Open QSO logging with call
  application/controllers/Qso.php
  application/views/bandmap/list.php
  application/views/qso/index.php
  application/views/qso/log_qso.php
  assets/js/sections/bandmap_list.js
  assets/js/sections/qso.js
Labels: enhancement

#1044 Prevent endless looping in case of br0ken ADIFs
  application/libraries/Adif_parser.php
  application/models/Logbook_model.php
Labels: bug

#1049 LoTW Tooltip Bug in QSO logging
  application/views/qso/index.php
  assets/js/sections/qso.js
Labels: bug, frontend, language

#1054 Session Management - Too many old session files
  application/config/config.sample.php
  install/config/config.php
  system/libraries/Session/Session.php
Labels: enhancement

#1063 Only select needed columns (and avoid dupe names)
  application/models/Logbook_model.php
Labels: bug

#1064 Use QSLRDATE provided by eqsl.cc (current date only as fallback)
  application/libraries/EqslImporter.php
  application/models/Eqslmethods_model.php
  application/views/eqsl/analysis.php
Labels: enhancement

#1065 Show fail date only if failed indeed
  application/views/lotw_views/index.php
Labels: enhancement, frontend

#1067 API response to show processed and failed ADIF items
  application/controllers/Api.php
Labels: enhancement

#1071 Align visitor view for logged-in users (cosmetical)
  application/views/visitor/index.php
Labels: frontend

#1075 bindings
  application/controllers/Band.php
  application/controllers/Gridmap.php
  application/controllers/Oqrs.php
  application/controllers/Widgets.php
  application/models/Activated_gridmap_model.php
  application/models/Bands.php
  application/models/Gridmap_model.php
  application/models/Oqrs_model.php
  assets/js/sections/gridmap.js
  assets/js/sections/oqrs.js
Labels: security

#1072 [INSTALLER] Bugfixes and Callsign Check
  application/migrations/215_add_contest_settings.php
  install/includes/interface_assets/footer.php
  install/index.php
Labels: bug, enhancement, installer

#1086 Added Baltic Languages
  application/config/gettext.php
  application/locale/et/LC_MESSAGES/index.html
  application/locale/et/LC_MESSAGES/messages.po
  application/locale/lt/LC_MESSAGES/index.html
  application/locale/lt/LC_MESSAGES/messages.po
  application/locale/lv/LC_MESSAGES/index.html
  application/locale/lv/LC_MESSAGES/messages.po
  application/views/debug/index.php
  install/includes/gettext/gettext_conf.php
  install/includes/gettext/locale/et/LC_MESSAGES/installer.po
  install/includes/gettext/locale/lt/LC_MESSAGES/installer.po
  install/includes/gettext/locale/lv/LC_MESSAGES/installer.po
  install/includes/interface_assets/footer.php
Labels: language

#1105 Fix radio value = 0
  application/views/qso/index.php
Labels: bug

#1106 QSLMSG in API Imports
  application/controllers/Qso.php
  application/models/Logbook_model.php
Labels: bug

#1117 Invalid CQ Zone Value
  assets/js/sections/qso.js
Labels: bug

#1122 Added "Mark QSL requested (Bureau)"
  application/views/search/search_result_ajax.php
  application/views/view_log/partial/log.php
  application/views/view_log/partial/log_ajax.php
Labels: enhancement, frontend

#1126 Update/add MESAT and SONATE-2 and reset LoTW upload for those
  application/config/migration.php
  application/migrations/225_lotw_satupdate_mesat_sonate.php
Labels: enhancement

#1121 Fix LBA issue with CQZ 0 and remove some ucwords from DXCC NONE
  application/models/Dxcc.php
  application/views/logbookadvanced/index.php
  application/views/lookup/index.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  application/views/view_log/qso.php
  src/QSLManager/QSO.php
Labels: bug, enhancement

#1129 Make wording more precise
  application/views/dashboard/index.php
Labels: enhancement

#1139 Change Countries to DXCCs in visitor's view
  application/views/visitor/index.php
Labels: frontend

#1098 Static Map API
  application/controllers/Adif.php
  application/controllers/Staticmap.php
  application/controllers/Station.php
  application/controllers/Visitor.php
  application/libraries/Genfunctions.php
  application/libraries/Qra.php
  application/models/Logbook_model.php
  application/models/Logbooks_model.php
  application/models/Staticmap_model.php
  application/models/Stations.php
  application/models/Stationsetup_model.php
  application/models/Themes_model.php
  application/models/User_model.php
  application/models/Visitor_model.php
  application/views/debug/index.php
  application/views/stationsetup/exportmapoptions.php
  assets/json/geojson/cqzones.geojson
  assets/json/geojson/ituzones.geojson
  src/StaticMap/LICENSE
  src/StaticMap/README.md
  src/StaticMap/src/Circle.php
  src/StaticMap/src/Geometry2D.php
  src/StaticMap/src/Image.php
  src/StaticMap/src/Interfaces/Draw.php
  src/StaticMap/src/LatLng.php
  src/StaticMap/src/Line.php
  src/StaticMap/src/MapData.php
  src/StaticMap/src/Markers.php
  src/StaticMap/src/OpenStreetMap.php
  src/StaticMap/src/Polygon.php
  src/StaticMap/src/TileLayer.php
  src/StaticMap/src/Utils/GeographicConverter.php
  src/StaticMap/src/Utils/Terminator.php
  src/StaticMap/src/XY.php
  src/StaticMap/src/resources/circle-dot-red.png
  src/StaticMap/src/resources/font.ttf
  src/StaticMap/src/resources/watermark_static_map.png
Labels: enhancement, new feature
