Repository wavelog/wavelog, pull requests merged in 2024-12, with the labels that each got.

#1295 Fixed Bandmap Bug II
  assets/js/sections/bandmap_list.js
Labels: bug

#1297 Set QRZ only to "M" if uploaded/invalid before
  application/models/Logbookadvanced_model.php
Labels: bug

#1301 Country sat records
  application/models/Distancerecords_model.php
  application/views/view_log/partial/log_ajax.php
Labels: bug

#1296 Restore uppercase transformation for inputs
  application/views/contesting/index.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  assets/css/general.css
Labels: frontend

#996 Refactor SAT stuff
  application/config/migration.php
  application/controllers/Logbook.php
  application/controllers/Lotw.php
  application/controllers/Satellite.php
  application/controllers/Update.php
  application/migrations/228_rename_satellites.php
  application/models/Distancerecords_model.php
  application/models/Distances_model.php
  application/models/Logbook_model.php
  application/models/Satellite_model.php
  application/models/Timeline_model.php
  application/views/distancerecords/index.php
  application/views/lotw_views/adif_views/adif_export.php
  application/views/satellite/create.php
  application/views/satellite/edit.php
  application/views/satellite/index.php
  application/views/view_log/partial/log_ajax.php
  application/views/view_log/qso.php
  assets/js/sections/satellite.js
Labels: enhancement, frontend

#1310 userlist - Allow click on E-Mail to open default mail software
  application/views/user/index.php
Labels: enhancement, frontend

#1303 Make orbit dropdown aka. fences everywhere
  application/views/satellite/create.php
  application/views/satellite/edit.php
Labels: frontend

#1304 LoTW SAT name should not be required
  application/views/satellite/create.php
  application/views/satellite/edit.php
  assets/js/sections/satellite.js
Labels: frontend

#1302 Fix country name in timeline views
  application/models/Timeline_model.php
Labels: bug

#1307 [Installer] better debugging
  application/controllers/Update.php
  install/includes/core/core_class.php
  install/includes/core/database_class.php
  install/index.php
  install/run.php
  system/libraries/Migration.php
Labels: installer

#1319 Remove ambiguity for sat and country name from search results
  application/controllers/Logbook.php
Labels: bug

#1318 Don't save and process empty files for QRZ
  application/controllers/Qrz.php
Labels: bug

#1322 Refactor SAT passes table
  application/views/satellite/pass.php
  application/views/satellite/passtable.php
Labels: frontend

#1329 Punchcard
  application/controllers/Dayswithqso.php
  application/models/Dayswithqso_model.php
  application/views/dayswithqso/index.php
  assets/css/cyborg/overrides.css
  assets/css/cyborg_wide/overrides.css
  assets/css/darkly/overrides.css
  assets/css/darkly_wide/overrides.css
  assets/css/general.css
  assets/css/superhero/overrides.css
  assets/css/superhero_wide/overrides.css
  assets/js/jquery.glanceyear.js
  assets/js/sections/dayswithqso.js
Labels: enhancement, frontend

#1323 Resolve PHP errors and display angles correctly
  application/views/sattimers/index.php
Labels: bug, frontend

#1330 Maptile Settings in Global Options
  application/controllers/Options.php
  application/models/Staticmap_model.php
  application/views/interface_assets/footer.php
  application/views/options/maptiles.php
  application/views/options/sidebar.php
  application/views/visitor/exportmap/exportmap.php
  application/views/visitor/exportmap/footer.php
  application/views/visitor/layout/footer.php
  assets/js/leaflet/leaflet.js
Labels: enhancement

#1343 Fix correct check for empty date
  application/models/Logbook_model.php
Labels: bug

#1342 Skip Users without any station_id at lotw_download
  application/controllers/Lotw.php
  application/models/Logbook_model.php
Labels: bug

#1338 Function to add/update SAT data from tqsl/LoTW config file
  application/controllers/Update.php
  application/models/Update_model.php
  application/views/lotw/satupdate.php
  application/views/satellite/index.php
Labels: frontend, new feature

#1320 PHP 8.4 readiness
  system/core/Exceptions.php
  system/libraries/Session/Session.php
Labels: bug

#1357 Add option to enable eqsl massdownload
  application/config/config.sample.php
  application/controllers/Eqsl.php
  application/views/eqsl/download.php
  install/config/config.php
Labels: security

#1313 ADIF Standard Version 3.1.5
  application/config/migration.php
  application/controllers/Adif.php
  application/controllers/Api.php
  application/libraries/AdifHelper.php
  application/migrations/231_adif_315.php
  application/models/Logbook_model.php
  application/views/adif/data/clublog.php
  application/views/adif/data/exportall.php
  application/views/adif/data/exportsat.php
  application/views/adif/import.php
  application/views/backup/exportall.php
  application/views/interface_assets/footer.php
  assets/js/sections/common.js
  src/QSLManager/QSO.php
Labels: enhancement, major impact, Library Update

#1353 Previous QSL Check
  application/controllers/Qslprint.php
  application/models/Qslprint_model.php
  application/views/qslprint/index.php
  application/views/qslprint/qslprint.php
  assets/js/sections/qslprint.js
Labels: enhancement

#1367 Fixes "sticking" Mail
  assets/js/sections/qso.js
Labels: bug

#1373 Added Region to logging/edit
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  application/views/view_log/qso.php
  assets/js/sections/qso.js
Labels: Wait for other PR

#1380 Fixes bug at JS when trying to log call with multiple zeros
  assets/js/sections/qso.js
Labels: bug

#1400 show eqsl images in LBA in the same way as in Logbook Overview
  src/QSLManager/QSO.php
Labels: frontend

#1399 Share Modal
  application/controllers/Qso.php
  application/views/interface_assets/footer.php
  application/views/qso/components/share_modal.php
  application/views/view_log/qso.php
  assets/css/general.css
  assets/js/sections/common.js
Labels: enhancement, frontend

#1414 Fixes search for calls with 0 at eQSL and QSL Datatable
  application/views/interface_assets/footer.php
Labels: bug, frontend

#1413 Calculate and fill distance (API)
  application/controllers/Api.php
Labels: enhancement

#1407 If there was an error at inserting QSO via API, return 400
  application/controllers/Api.php
Labels: bug, API

#1402 CleanUp primary_subdivisions and adif_modes before doing mig
  application/migrations/231_adif_315.php
Labels: bug, database

#1415 Update DXCC coming from LoTW to Log
  application/controllers/Lotw.php
  application/models/Logbook_model.php
Labels: bug
