Repository wavelog/wavelog, pull requests merged in 2024-11, with the labels that each got.

#1147 Exclude NONE DXCC for cfd exports
  application/controllers/Cfdexport.php
Labels: bug

#1148 Clublog hint about app passwords if 2FA is enabled
  application/views/user/edit.php
Labels: frontend

#1136 Translated E-Mails
  application/controllers/Options.php
  application/controllers/Oqrs.php
  application/controllers/User.php
  application/views/email/admin_reset_password.php
  application/views/email/forgot_password.php
  application/views/email/oqrs_request.php
  application/views/email/testmail.php
  system/libraries/Email.php
Labels: enhancement, language

#1149 Remove DXCC NONE from DXCC award
  application/controllers/Awards.php
Labels: bug, frontend

#1150 (Re-)Include 160m into cfd exports
  application/models/Logbook_model.php
Labels: bug

#1152 Clear distance (and bearing display) if grid is empty(ed)
  assets/js/sections/qso.js
Labels: bug, frontend

#1154 Add orbit type to static maps for SAT QSOs
  application/controllers/Staticmap.php
  application/models/Visitor_model.php
Labels: enhancement

#1142 [SimpleFLE] Fixed an issue at saving QSOs
  application/controllers/Simplefle.php
  application/views/interface_assets/footer.php
  application/views/simplefle/index.php
  application/views/user/index.php
  assets/js/sections/simplefle.js
Labels: bug

#1156 library for trx-control
  application/config/config.sample.php
  application/libraries/Trxd.php
  install/config/config.php
Labels: enhancement

#1158 Staticmap - Options for Contest and Date Range
  application/controllers/Staticmap.php
  application/models/Visitor_model.php
Labels: enhancement

#1161 Fix Cronmanager Reload Button
  application/controllers/Cron.php
Labels: bug, frontend

#1162 QSO Edit Modal
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  assets/js/sections/common.js
Labels: frontend

#1166 Show prop mode in QSO view
  application/views/view_log/qso.php
Labels: enhancement, frontend

#1169 Autocomplete and Pretty zeros
  application/views/contesting/index.php
  application/views/interface_assets/footer.php
  application/views/qso/index.php
  application/views/search/result.php
  assets/css/general.css
Labels: frontend

#1167 Skip AMSAT status upload for invalid/non-existent grids
  application/models/Logbook_model.php
Labels: bug

#1168 Adjust regex to accept VUCC grids (again)
  application/controllers/Logbookadvanced.php
Labels: bug

#1172 Unit distance sort
  application/controllers/Distancerecords.php
  application/models/Distancerecords_model.php
  application/views/distancerecords/index.php
  application/views/interface_assets/footer.php
Labels: enhancement, frontend

#1177 php-gd in Docker
  Dockerfile
  install/includes/install_config/install_config.php
Labels: enhancement

#1182 Static Map - Some improvements
  application/controllers/Staticmap.php
  application/models/Staticmap_model.php
  application/models/Visitor_model.php
  src/StaticMap/src/LatLng.php
  src/StaticMap/src/Line.php
  src/StaticMap/src/Markers.php
Labels: enhancement

#1175 Show DXCC as badge with status in the search results
  application/controllers/Logbook.php
  application/models/Logbook_model.php
  application/views/search/result.php
Labels: frontend

#1184 Extend SIG-Cols in Database
  application/config/migration.php
  application/migrations/227_extend_sig_info.php
Labels: bug, database

#1186 Changed cat_url to VARCHAR(255)
  application/migrations/226_add_cat_url.php
Labels: bug

#1190 [QSO] Bug in Start Timer
  assets/js/sections/qso.js
Labels: bug

#1193 Omit various fields for dynamic callsigns (/P, /M, /MM, ...)
  application/controllers/Logbook.php
  application/models/Logbook_model.php
Labels: enhancement

#1195 QSO - More efficient DXCC Summary
  application/controllers/Lookup.php
  application/views/lookup/result.php
  assets/js/sections/common.js
Labels: enhancement

#1202 Update From Callbook also Continent
  application/models/Logbook_model.php
  application/models/Logbookadvanced_model.php
Labels: enhancement

#1198 Cabrillo Fix
  application/controllers/Cabrillo.php
  application/libraries/Cabrilloformat.php
  application/views/cabrillo/export.php
  application/views/cabrillo/index.php
  assets/js/sections/contesting.js
Labels: bug

#1209 escape single quotation marks
  install/includes/core/database_class.php
Labels: bug, installer

#1196 Enhanced QRG Input
  application/controllers/User_options.php
  application/views/bands/index.php
  application/views/contesting/index.php
  application/views/interface_assets/footer.php
  application/views/qso/index.php
  assets/js/sections/contesting.js
  assets/js/sections/qrg_handler.js
  assets/js/sections/qso.js
Labels: enhancement

#1221 Staticmap Watermark
  application/controllers/Staticmap.php
  application/models/Staticmap_model.php
Labels: enhancement

#1165 Antenna Path in QSO Logging and QSO Details
  application/controllers/Logbook.php
  application/libraries/Qra.php
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  application/views/view_log/qso.php
  assets/js/sections/common.js
  assets/js/sections/qso.js
Labels: enhancement

#1237 QSO Edit HTML ID's fix
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  assets/js/sections/common.js
Labels: bug

#1240 Added whitespace
  application/models/Timeline_model.php
Labels: bug

#1239 Enable at least the manual uploading of a file for LoTW
  application/controllers/Lotw.php
  application/views/lotw/import.php
  application/views/lotw_views/index.php
Labels: enhancement

#1245 Distances at ADIF must be in km at any time
  application/models/Distances_model.php
Labels: bug

#1246 Correct wording
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
  application/views/view_log/qso.php
Labels: frontend

#1248 Fetch email from callbook / last QSOs
  application/controllers/Logbook.php
  application/libraries/Hamqth.php
  application/libraries/Qrz.php
  application/models/Logbook_model.php
  assets/js/sections/qso.js
Labels: frontend

#1243 Make LoTW-Downloads threadsafe
  application/controllers/Lotw.php
Labels: bug, enhancement

#1244 Make QRZ-Download threadsafe
  application/controllers/Qrz.php
Labels: bug, enhancement

#1254 Update map when entering POTA/SOTA/WWFF
  application/views/interface_assets/footer.php
Labels: bug

#1266 QRG Unit - allow short input aswell
  assets/js/sections/qrg_handler.js
Labels: enhancement

#1265 Display a numeric keyboard for number input fields
  application/views/qso/index.php
Labels: frontend

#1272 Numblock for mobile
  assets/js/sections/contesting.js
  assets/js/sections/qrg_handler.js
  assets/js/sections/qso.js
Labels: enhancement

#1270 fix quicklog feature
  assets/js/sections/qso.js
Labels: bug

#1278 Fixed clublog-icon
  application/views/view_log/partial/log_ajax.php
Labels: bug

#1271 QSL Tab Fix in edit modal
  application/views/qso/edit_ajax.php
Labels: bug, frontend

#1284 Exceptionhandling for missing/wrong mode at QRZ
  application/controllers/Qrz.php
Labels: bug

#1279 Show invalid eQSL QSL state in LBA
  assets/css/general.css
  src/QSLManager/QSO.php
Labels: frontend
