Repository wavelog/wavelog, pull requests merged in 2025-07, with the labels that each got.

#2089 Separate table ids
  application/controllers/Awards.php
  application/controllers/Statistics.php
  application/views/awards/details.php
  application/views/interface_assets/footer.php
  application/views/statistics/details.php
  application/views/view_log/partial/log_ajax.php
  assets/js/sections/distancerecords.js
  assets/js/sections/distances.js
  assets/js/sections/ffma.js
  assets/js/sections/gridmap.js
  assets/js/sections/gridmaster.js
  assets/js/sections/statistics.js
Labels: bug, frontend

#2091 Refactor LoTW users update and prevent table from being emptied if file cannot be downloaded or is corrupt
  application/models/Update_model.php
Labels: bug

#2094 Exclude DXCC none from counter
  application/models/Dxcc.php
  application/models/Logbook_model.php
Labels: bug, frontend

#2096 Do not run calcs if sat list is empty
  application/views/satellite/pass.php
  assets/js/sections/satpasses.js
Labels: frontend

#2104 Add SAT summary to table
  application/controllers/Awards.php
  application/controllers/Lookup.php
  application/models/Logbook_model.php
  application/models/Lookup_model.php
  application/views/lookup/satresult.php
  application/views/qso/award_tabs.php
  assets/js/sections/qso.js
Labels: enhancement, frontend

#2114 Datatable usage for SOTA
  application/views/awards/sota/index.php
  application/views/interface_assets/footer.php
Labels: frontend

#2122 Use displayname incase LoTW name is not set (yet)
  application/models/Satellite_model.php
  application/views/satellite/flightpath.php
  assets/js/sections/flightpath.js
Labels: frontend

#2126 Add gridsquare to confirmations
  application/models/Qsl_model.php
  application/views/qslcard/confirmationresult.php
Labels: frontend

#2134 Fixes the "select-all" bug
  assets/js/sections/logbookadvanced.js
Labels: bug, frontend

#2163 Add newlines
  application/controllers/Lotw.php
Labels: frontend

#2164 Fix LoTW upload check
  application/controllers/Lotw.php
Labels: bug

#2183 better use site_url() instead base_url() to include index page (if set)
  application/views/api/index.php
  application/views/debug/index.php
  application/views/interface_assets/footer.php
Labels: enhancement, frontend

#2192 Fix QRZ
  application/models/Logbook_model.php
Labels: bug

#2193 Check mail for dupes b4 editing it
  application/controllers/User.php
  application/models/User_model.php
Labels: bug

#2199 Fixes Az/Ele Calculation with respect to the user_date_format
  assets/js/sections/qso.js
Labels: bug
