Repository wavelog/wavelog, pull requests merged in 2025-05, with the labels that each got.

#1924 Show wrong gridsquare in distances
  application/models/Distances_model.php
Labels: enhancement

#1929 Fix SQL group by error in QSL queue
  application/models/Qslprint_model.php
Labels: bug

#1921 Buffering qsos when (temporary) offline
  assets/js/sections/qso.js
Labels: enhancement

#1931 Update cache folder path in index.php
  application/views/debug/index.php
Labels: frontend

#1937 Make SIG use the correct description/references from ADIF standard
  application/views/awards/sig/index.php
  application/views/station_profile/create.php
  application/views/station_profile/edit.php
Labels: frontend

#1925 Move grid validation to library and also use in station locations
  application/controllers/Station.php
  application/controllers/User.php
  application/libraries/Qra.php
  application/views/station_profile/create.php
  application/views/station_profile/edit.php
  application/views/user/edit.php
Labels: enhancement, frontend, fence

#1945 QSLprint CSV Export - Added Submode in CSV data
  application/controllers/Qslprint.php
Labels: enhancement

#1949 Replace 0 by slahed version in LoTW report
  application/controllers/Lotw.php
Labels: frontend

#1950 Add some hyperlinks to WWFF award page
  application/views/awards/pota/index.php
  application/views/awards/wwff/index.php
Labels: enhancement, frontend

#1952 Show LoTW confirmed gridsquare even if not updated in DB
  application/controllers/Lotw.php
Labels: bug

#1958 Add Exch (S) to LBA edit function
  application/models/Logbookadvanced_model.php
  application/views/logbookadvanced/edit.php
  assets/js/sections/logbookadvanced_edit.js
Labels: enhancement, frontend

#1959 Get rid of config directory for clublog uploads
  application/models/Clublog_model.php
Labels: not a bug

#1963 Rename reset button in public search result table
  application/views/visitor/layout/footer.php
Labels: frontend

#1960 Add parameter to static map to show only today's (or yesterday's) QSOs
  application/controllers/Staticmap.php
  application/models/Visitor_model.php
Labels: enhancement, frontend

#1969 Added mime-definitions (in case of...)
  application/config/mimes.php
Labels: enhancement, fence

#1982 Add 4m to radiohelpers JS
  assets/js/radiohelpers.js
Labels: frontend

#1986 Make sure empty options are printed with any value
  application/controllers/Logbookadvanced.php
  application/views/logbookadvanced/index.php
Labels: bug, fence

#2000 Added hint for UTC to syncs
  application/views/clublog/export.php
  application/views/eqsl/import.php
  application/views/qrz/export.php
Labels: frontend
