Repository wavelog/wavelog, pull requests merged in 2025-10, with the labels that each got.

#2362 Notes overhaul: updated view of the notes, added "Contacts" category with required logic, first step for callsign sticky notes
  application/controllers/Notes.php
  application/models/Note.php
  application/views/interface_assets/footer.php
  application/views/notes/add.php
  application/views/notes/edit.php
  application/views/notes/main.php
  application/views/notes/view.php
  assets/js/sections/notes.js
Labels: enhancement, frontend

#2378 Add (current) streak to motivation Banner
  application/controllers/Dashboard.php
  application/views/dashboard/index.php
Labels: enhancement

#2397 Prevent clearing/updating TLEs if incoming file size is zero
  application/models/Update_model.php
Labels: bug
