Repository wavelog/wavelog, pull requests merged in 2025-06, with the labels that each got.

#2008 Make note about contest imports look less error-like
  application/views/adif/import_success.php
Labels: frontend

#2010 Determine DX gridsquare by clicking map
  application/controllers/Qso.php
  application/views/interface_assets/footer.php
Labels: frontend

#2014 allow propagation in logbook overview as column
  application/views/user/edit.php
  application/views/view_log/partial/log_ajax.php
Labels: enhancement

#2021 Persist after edit at SAT-Editor
  assets/js/sections/satellite.js
Labels: enhancement, frontend

#2022 Multi sat
  application/controllers/Satellite.php
  application/views/satellite/pass.php
  application/views/satellite/skedtable.php
  assets/css/general.css
  assets/js/sections/satpasses.js
Labels: enhancement, frontend

#2032 Fix LoTW-Link
  application/views/lotw/import.php
Labels: frontend

#2035 Show amount of marked QSOs in LBA, when deleting them
  application/views/logbookadvanced/index.php
  assets/js/sections/logbookadvanced.js
Labels: frontend

#2037 Amsat only accept 6 char-grids, so trunc them
  application/models/Logbook_model.php
Labels: bug, 3rd-party stuff related

#2039 Show error message in case ant el is (too) negative
  application/views/qso/index.php
  assets/js/sections/qso.js
Labels: frontend

#2046 concat to $log throws an error, because it isn't defined
  application/models/Clublog_model.php
Labels: bug

#2049 Add DXCC flags to LBA view
  application/controllers/Logbookadvanced.php
  assets/js/sections/logbookadvanced.js
  src/QSLManager/QSO.php
Labels: enhancement, frontend

#2056 DXCC ADIF-Export and Flag-Fix
  application/controllers/Logbookadvanced.php
  application/models/Logbookadvanced_model.php
  assets/js/sections/logbookadvanced.js
Labels: bug

#2060 Added mapping for esoteric TRX (USB-D1 instead of USB, etc.)
  application/controllers/Api.php
Labels: enhancement

#2071 allow for emptying grid in LBA edit function
  application/models/Logbookadvanced_model.php
Labels: frontend
