Repository wavelog/wavelog, pull requests merged in 2025-02, with the labels that each got.

#1598 Take ONLY Datepart if looking up a DXCC
  application/models/Logbook_model.php
Labels: bug

#1601 Use PK as secondary sorting criteria (as in other places)
  application/controllers/Logbook.php
  application/models/Logbook_model.php
Labels: bug

#1607 Again Zero-Problems - now at Userlist
  assets/js/sections/user.js
Labels: bug

#1604 Used wrong key when disabling clublog
  application/models/Clublog_model.php
  application/models/Logbook_model.php
Labels: bug

#1613 Replace 0 by Ø in awards table search input
  application/views/interface_assets/footer.php
  application/views/view_log/partial/log_ajax.php
Labels: enhancement, frontend

#1614 Observe DOM since it mutates during render
  application/views/interface_assets/footer.php
Labels: bug

#1623 Small one: fixing Lookup-behaviour
  application/views/lookup/index.php
Labels: bug, frontend

#1624 Fixes two issues at DOK-Lookup. Pre/Suffix and crappy Zero(tm)
  application/controllers/Lookup.php
  assets/js/sections/qso.js
Labels: bug

#1628 Add link to QSO view to eQSL card download page
  application/views/eqsl/download.php
Labels: enhancement, frontend

#1629 Trim \r\n\t on ADIF before parsing JSON
  application/controllers/Api.php
Labels: enhancement

#1632 Fix JS copy functions for API URL and KEY
  application/views/interface_assets/footer.php
Labels: bug

#1622 Upgrade DataTable-Lib
  application/views/interface_assets/footer.php
  application/views/logbookadvanced/index.php
  assets/css/datatables.min.css
  assets/js/dataTables.buttons.min.js
  assets/js/datatables.min.js
  assets/js/sections/bandmap_list.js
  assets/js/sections/distances.js
  assets/js/sections/gridmap.js
  assets/js/sections/logbookadvanced.js
  assets/js/sections/logbookadvanced_edit.js
  assets/js/sections/logbookadvanced_map.js
Labels: enhancement, frontend

#1634 Qslmsg labels print
  application/controllers/Labels.php
  application/views/labels/startatform.php
  application/views/logbookadvanced/startatform.php
  assets/js/sections/logbookadvanced.js
Labels: enhancement

#1641 Allow freetext for operator
  application/views/adif/import.php
Labels: enhancement, frontend

#1635 Fixed current QRG-Display at bandmap
  assets/css/darkly/overrides.css
  assets/js/sections/bandmap_list.js
Labels: bug

#1645 Add prop mode to check
  application/controllers/Lotw.php
  application/controllers/Qrz.php
  application/libraries/EqslImporter.php
  application/models/Eqslmethods_model.php
  application/models/Logbook_model.php
Labels: bug

#1651 Link QSO view in download reports
  application/controllers/Lotw.php
  application/controllers/Qrz.php
  application/views/eqsl/analysis.php
Labels: enhancement, frontend

#1652 Prevent mysql error on editing
  application/controllers/Qso.php
  application/models/Logbook_model.php
Labels: bug, database

#1664 Order station-locations by call and description
  application/models/Stations.php
Labels: enhancement, frontend

#1662 Forgotten victim of new datatable
  assets/js/sections/hamsat.js
Labels: bug, frontend

#1657 Fixed dropdowns on mobile devices
  application/views/interface_assets/header.php
Labels: frontend

#1659 Edit fence
  application/controllers/Qso.php
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  assets/js/sections/common.js
Labels: enhancement

#1668 Make dashboard-map user-configurable
  application/controllers/Dashboard.php
  application/controllers/Options.php
  application/controllers/User.php
  application/models/User_model.php
  application/views/dashboard/index.php
  application/views/options/appearance.php
  application/views/user/edit.php
Labels: frontend

#1680 Replace all slahsed zeros in qrz/hamqth link
  assets/js/sections/qso.js
Labels: bug, frontend

#1678 Added RTTY-Translations for Yaesu and icom
  application/controllers/Api.php
Labels: enhancement

#1690 List SATs with only displayname and prevent QSO being made via those from being uploaded to LoTW
  application/models/Logbook_model.php
  application/models/Satellite_model.php
Labels: enhancement, frontend

#1685 Added fence. ReUpload only to QRZ if really modified
  application/models/Logbook_model.php
Labels: bug

#1686 Added safety-net if last_worked isn't filled yet
  assets/js/sections/bandmap_list.js
Labels: bug, frontend

#1696 List satellites in edit dropdown alphabetically
  application/models/Satellite_model.php
Labels: frontend

#1697 Added important notice to add_user at User_model
  application/models/User_model.php
Labels: documentation

#1698 Widget error message formatting
  application/controllers/Widgets.php
  application/migrations/237_user_callsign_public_slug.php
  application/views/widgets/on_air.php
Labels: frontend

#1702 Fix accidently removed line for updating log when QSL was sent
  application/models/Logbook_model.php
Labels: bug

#1704 Add info / link for WAE award
  application/views/awards/wae/index.php
Labels: enhancement

#1707 Correct description for month of the year QSOs
  application/views/dayswithqso/index.php
  assets/js/sections/dayswithqso.js
Labels: bug

#1710 Add 73on73 SAT award
  application/controllers/Awards.php
  application/models/Seven3on73.php
  application/views/awards/73on73/index.php
  application/views/interface_assets/header.php
Labels: enhancement, frontend

#1708 Pan map on station profile select
  application/controllers/Station.php
  application/models/Stations.php
  application/views/qso/index.php
  assets/js/sections/qso.js
Labels: frontend
