Repository wavelog/wavelog, pull requests merged in 2025-04, with the labels that each got.

#1829 Trim Space for Call at QSO-form at JS and last-defense saving
  application/models/Logbook_model.php
  assets/js/sections/qso.js
Labels: bug

#1835 Make order_by more safe
  application/models/Logbookadvanced_model.php
Labels: security

#1828 Ignore empty QSL-Fields on empty/import
  application/models/Logbook_model.php
Labels: enhancement

#1837 Check power for valid string/number, otherwise ignore
  application/models/Cat.php
Labels: fence

#1841 Add foreign key constraint also to satmode table
  application/config/migration.php
  application/migrations/241_satmode_fk.php
Labels: enhancement

#1839 Add markers to +/- 90 min position
  assets/js/sections/flightpath.js
Labels: frontend

#1846 Reset distance-Field on new QSO/reset
  assets/js/sections/qso.js
Labels: bug

#1859 Dead links
  application/controllers/Awards.php
  application/views/awards/counties/index.php
  application/views/awards/cq/index.php
  application/views/interface_assets/header.php
Labels: frontend

#1858 fix[installer] make sure the correct config dir is created if not existent
  .gitignore
  install/includes/core/core_class.php
Labels: installer

#1868 QRZ.ru in the Installer
  install/includes/core/core_class.php
  install/index.php
Labels: installer

#1877 Add option to switch on callsings for all LBA map markers
  application/views/logbookadvanced/index.php
  assets/css/general.css
  assets/js/sections/logbookadvanced_map.js
Labels: enhancement, frontend

#1885 Truncate HoN input
  application/models/Update_model.php
  application/views/qso/index.php
  application/views/update/hamsofnote.php
  assets/js/sections/qso.js
Labels: fence

#1869 Mqtt streaming for whole instance
  application/libraries/Mh.php
  application/models/Cat.php
  application/models/Logbook_model.php
  application/models/Stations.php
  src/phpMQTT.php
Labels: enhancement, new feature, 3rd-party stuff related

#1889 Feature to save pass prediction settings
  application/controllers/Satellite.php
  application/views/interface_assets/footer.php
  application/views/satellite/pass.php
  application/views/satellite/passtable.php
  application/views/satellite/tleinfo.php
  assets/js/sections/flightpath.js
  assets/js/sections/satpasses.js
Labels: enhancement

#1887 Handle SAT as band for lookups
  assets/js/sections/common.js
  assets/js/sections/qso.js
Labels: frontend
