Repository wavelog/wavelog, pull requests merged in 2025-01, with the labels that each got.

#1418 views: eqslcard: add ability to navigate between eqsl cards
  application/views/eqslcard/index.php
Labels: enhancement, frontend

#1420 Add custom date format for system time display
  application/controllers/Debug.php
  application/views/debug/index.php
Labels: frontend

#1425 Last wked
  application/models/Dxcluster_model.php
  application/models/Logbook_model.php
  application/views/bandmap/list.php
  assets/js/sections/bandmap_list.js
Labels: enhancement, frontend

#1426 Trigger recheck work/cnf state on modechange
  assets/js/sections/qso.js
Labels: bug

#1429 make user roles translatable
  application/controllers/Club.php
Labels: enhancement

#1437 Also fill email upon single callbook update
  assets/js/sections/common.js
Labels: bug

#1431 show user_name in dropdown for clubstations
  application/controllers/Club.php
  application/models/User_model.php
  assets/js/sections/club_permissions.js
Labels: enhancement

#1433 [WIP] Cluboptimizing
  application/controllers/Api.php
  application/controllers/Bandmap.php
  application/controllers/Club.php
  application/migrations/233_clubstations.php
  application/models/Cat.php
  application/views/user/index.php
Labels: database

#1450 Don't disable button if no file was chosen
  assets/js/sections/adif.js
Labels: bug, frontend

#1453 Only show the most critical warning and link to LoTW
  application/views/dashboard/index.php
Labels: enhancement, frontend

#1454 Remove old-stuff ("Custom-Stat")
  application/controllers/Statistics.php
  application/models/Logbook_model.php
  application/views/statistics/custom.php
  application/views/statistics/custom_result.php
Labels: bug, security

#1452 Fallback for DXCC data
  application/controllers/Update.php
Labels: enhancement

#1458 Escape quotes in json to prevent the share modal from failing
  application/views/view_log/qso.php
Labels: bug

#1462 Fix advanced search
  application/controllers/Search.php
  application/views/interface_assets/footer.php
Labels: bug

#1465 Skip LoTW-Input for records without a station_callsign
  application/controllers/Lotw.php
Labels: bug

#1467 Keep SAT frequencies on mode change
  assets/js/sections/qso.js
Labels: bug

#1472 show no clubs available only for admin
  application/views/interface_assets/header.php
Labels: frontend

#1469 Make column rename failsafe
  application/migrations/228_rename_satellites.php
Labels: bug

#1474 allow searching for first and lastname at the same time at club permissions
  application/models/User_model.php
Labels: enhancement

#1473 remove club permissions on conversion
  application/controllers/User.php
  application/models/User_model.php
Labels: bug

#1349 First Login Wizard
  application/controllers/Dashboard.php
  application/controllers/User.php
  application/models/User_model.php
  application/views/dashboard/index.php
  application/views/interface_assets/footer.php
  application/views/user/modals/first_login_wizard.php
  assets/css/general.css
  assets/js/sections/dashboard.js
Labels: enhancement

#1482 Make DARC DOK and other refs selectize input uppercase
  application/models/Logbook_model.php
  application/views/qso/edit_ajax.php
  application/views/qso/index.php
Labels: frontend

#1485 Add bearing to Dashboard/Overview/Map
  application/models/Logbook_model.php
  application/views/dashboard/index.php
  application/views/user/edit.php
  application/views/view_log/partial/log_ajax.php
Labels: enhancement, frontend

#1484 fix reset_time button to actually reset the time
  assets/js/sections/qso.js
Labels: bug

#1496 Show flag only if not empty
  assets/js/sections/logbookadvanced_map.js
Labels: frontend

#1499 Add units and make sortable
  application/views/logbookadvanced/index.php
  assets/js/sections/logbookadvanced.js
  src/QSLManager/QSO.php
Labels: frontend

#1500 Fallback to short-living-popup if fetch fails (cors-workaround)
  assets/js/sections/bandmap_list.js
Labels: bug

#1501 Fix for Last-QRZ-QSL
  application/controllers/Qrz.php
  application/models/Logbook_model.php
Labels: bug

#1506 show hint about qrz.com login credentials. QRZ.com needs your callsig…
  application/config/config.sample.php
  install/config/config.php
  install/index.php
Labels: enhancement

#1509 Import and show incoming (e)QSL messages
  application/controllers/Logbookadvanced.php
  application/libraries/EqslImporter.php
  application/models/Eqsl_images.php
  application/models/Eqslmethods_model.php
  application/views/eqsl/download.php
  application/views/eqslcard/index.php
  application/views/logbookadvanced/index.php
  application/views/logbookadvanced/useroptions.php
  application/views/qso/edit_ajax.php
  application/views/view_log/qso.php
  assets/js/sections/logbookadvanced.js
  src/QSLManager/QSO.php
Labels: enhancement, frontend

#1511 60m was missing for GetBand
  application/libraries/Frequency.php
Labels: bug

#1495 Brute force protection
  application/config/config.sample.php
  application/config/migration.php
  application/controllers/User.php
  application/migrations/234_login_attempts.php
  application/models/User_model.php
  application/views/user/index.php
  application/views/user/modals/more_actions_modal.php
  install/config/config.php
Labels: enhancement, security, new feature

#1520 Deactivate Clublog if auth-error
  application/models/Logbook_model.php
Labels: bug

#1529 Show Update Results in Debug Page as Flash Messages
  application/controllers/Update.php
  application/models/Update_model.php
Labels: enhancement

#1531 Make Old CSV-Export injection-safe (binding)
  application/models/Csv_model.php
Labels: security

#1539 ADIF Tabfix
  application/views/adif/import.php
Labels: bug

#1540 [Installer] Fixes
  application/config/config.sample.php
  install/config/config.php
  install/includes/interface_assets/footer.php
  install/index.php
  install/run.php
Labels: bug, installer

#1544 Added exception for /B Suffix at Call (shouldn't resolve to china)
  application/models/Logbook_model.php
  src/Dxcc/Dxcc.php
Labels: bug

#1543 Refactored lookup_model to bind (leftover)
  application/models/Lookup_model.php
Labels: security, database

#1545 added slovenian
  application/config/gettext.php
  application/locale/sl/LC_MESSAGES/index.html
  application/views/debug/index.php
  install/includes/gettext/gettext_conf.php
  install/includes/gettext/locale/sl/LC_MESSAGES/index.html
  install/includes/interface_assets/footer.php
Labels: language

#1562 Handle 2-char grids (prevent filling the error log)
  application/libraries/Qra.php
Labels: bug

#1483 Implement contest srx/stx and comments in SimpleFLE
  application/views/simplefle/index.php
  application/views/simplefle/syntax_help.php
  assets/js/sections/simplefle.js
Labels: enhancement

#1570 Use SAT export name if differs from name
  application/controllers/Hamsat.php
  assets/js/sections/hamsat.js
Labels: enhancement, frontend

#1580 Take Lat/Long from exceptions if exceptions are taken
  application/models/Logbook_model.php
Labels: bug

#1581 As shortcut replace dot by /P on callsign input
  assets/js/sections/qso.js
Labels: enhancement, frontend

#1584 Remove superfluous and unused function
  application/controllers/Clublog.php
Labels: API

#1583 Users Table
  application/config/config.sample.php
  application/models/User_model.php
  application/views/user/index.php
  install/config/config.php
Labels: enhancement

#1590 Fix region edit in LBA
  application/models/Logbookadvanced_model.php
Labels: bug

#1592 Fix clublog upload error message
  assets/js/sections/clublog.js
Labels: bug

#1593 More safe Club Log Handling to prevent being blacklisted
  application/models/Clublog_model.php
Labels: bug
