Repository wavelog/wavelog, pull requests merged in 2025-09, with the labels that each got.

#2283 Fix Typo for fresh installations
  application/migrations/197_clublog_recvd.php
  application/views/clublog/export.php
  application/views/eqsl/analysis.php
  application/views/eqsl/download.php
  application/views/eqsl/export.php
  application/views/eqsl/import.php
  application/views/eqsl/result.php
  application/views/eqsl/tools.php
  application/views/qrz/export.php
Labels: frontend, cosmetics

#2286 Prevent auto-usage from (probably) wrong qrz.com grids
  application/controllers/Logbook.php
  application/libraries/Callbook.php
  application/libraries/Qrz.php
  application/views/search/result.php
  assets/js/sections/qso.js
Labels: enhancement

#2284 Add POTA ref import function
  application/controllers/Adif.php
  application/models/Logbook_model.php
  application/views/adif/import.php
  application/views/adif/pota_success.php
Labels: enhancement

#2297 Set proper last_run for DCL-Cron
  application/controllers/Dcl.php
Labels: cosmetics

#2307 Mark DCL-Confirmed QSOs as RCVD regardless of DOK
  application/models/Logbook_model.php
Labels: enhancement, 3rd-party stuff related

#2309 Add hint to example tool
  application/views/adif/import.php
Labels: enhancement

#2315 Added Warning for Band-Edit
  application/views/bands/edit.php
Labels: fence

#2322 Save same space for master cron status OK
  application/views/cron/index.php
Labels: frontend

#2323 Allow LoTW confirmations including CNTY for some DXCCs
  application/controllers/Lotw.php
  application/views/lotw_views/adif_views/adif_export.php
Labels: enhancement

#2345 Suppress hyperlinks for zero cards
  application/views/dashboard/index.php
Labels: frontend

#2354 Fix wrong logic on solar data session value
  application/models/User_model.php
Labels: bug

#2355 Set last_run properly
  application/models/Update_model.php
Labels: bug

#2357 Set custom header (which can be processed by reverse proxy)
  application/controllers/User.php
Labels: security
