Repository wavelog/wavelog, pull requests merged in 2025-03, with the labels that each got.

#1706 Add distance calculation to contest logging
  application/models/Logbook_model.php
Labels: bug

#1700 [WIP]: Update LoTW QSL status for new/updated LoTW SAT info
  application/models/Update_model.php
Labels: enhancement

#1714 Fix Leftover - Wrong permission check
  application/controllers/User.php
Labels: bug

#1716 Very very strange bug. the ON-Clause for joining was wrong
  application/models/User_model.php
Labels: bug

#1725 Also search display contest name from contest table
  application/models/Logbookadvanced_model.php
Labels: bug

#1726 Use contest name in QSO view as well (as does LBA)
  application/models/Logbook_model.php
  application/views/view_log/qso.php
Labels: frontend

#1738 Add a progress indicator to LoTW manual sync and clear results upon (re-)click
  application/views/lotw_views/index.php
  assets/css/general.css
Labels: enhancement, frontend

#1737 Fix LBA search for SATs without LoTW name
  application/models/Logbookadvanced_model.php
Labels: bug

#1736 Add column with no of QSOs per satellite
  application/controllers/Satellite.php
  application/models/Logbook_model.php
  application/views/satellite/edit.php
  application/views/satellite/index.php
Labels: enhancement, frontend

#1741 Ignore country-column since dxcc is joined
  application/controllers/Lotw.php
  application/models/Logbook_model.php
  application/models/Timeline_model.php
Labels: bug

#1743 Make consequent use of NULL/1 and adjust defaults
  application/controllers/Awards.php
Labels: bug

#1742 Reset auto_increment to 1 before re-inserting user data
  application/models/Update_model.php
Labels: fence

#1745 Fix Map for DXCC as well (NULL/0)
  application/controllers/Awards.php
Labels: bug

#1746 Proposal for splitting SAT/HF at DXCC
  application/controllers/Awards.php
  application/models/Dxcc.php
  application/models/Iota.php
  application/views/awards/dxcc/index.php
  application/views/awards/iota/index.php
  assets/css/general.css
  assets/js/sections/dxccmap.js
Labels: enhancement

#1751 List QSOs on SAT in satellites page
  application/controllers/Statistics.php
  application/models/Stats.php
  application/views/satellite/index.php
  application/views/statistics/details.php
  application/views/statistics/satqsotable.php
  assets/js/sections/statistics.js
Labels: frontend

#1755 Fix syntax error
  application/models/Logbook_model.php
Labels: bug

#1754 Harmonize spelling of QSOs (was QSO's)
  application/models/Clublog_model.php
  application/views/activators/index.php
  application/views/adif/import.php
  application/views/callstats/index.php
  application/views/continents/index.php
  application/views/oqrs/qsolist.php
  application/views/qslprint/qsolist.php
  application/views/statistics/index.php
  application/views/timeline/index.php
Labels: frontend

#1759 Match satellite's tles via NORAD catalogue id
  application/config/migration.php
  application/migrations/238_add_norad_id_to_sat.php
  application/models/Update_model.php
Labels: enhancement, frontend

#1762 Order by col_time_on at eqsl-sync for upload (better debugging)
  application/models/Eqslmethods_model.php
Labels: enhancement

#1766 Fixes wrong amount of cols when SAT was never worked
  application/views/awards/dxcc/index.php
  application/views/awards/iota/index.php
Labels: bug

#1763 Reduce Grids / Take oldest
  application/models/Logbook_model.php
  application/models/Timeline_model.php
Labels: bug

#1750 Use values for grid, qth, state etc. from last QSO
  application/models/Logbook_model.php
Labels: frontend

#1765 strip < from qslmessage, because eqsl can't handle it
  application/controllers/Eqsl.php
  application/models/Eqslmethods_model.php
Labels: bug

#1769 [WIP] SAT-Improvements
  application/controllers/Satellite.php
  application/views/satellite/flightpath.php
  application/views/satellite/pass.php
  application/views/satellite/passtable.php
  application/views/satellite/schedule.php
  application/views/satellite/skedtable.php
  assets/fontawesome/css/all.min.css
  assets/fontawesome/webfonts/fa-brands-400.eot
  assets/fontawesome/webfonts/fa-brands-400.svg
  assets/fontawesome/webfonts/fa-brands-400.ttf
  assets/fontawesome/webfonts/fa-brands-400.woff
  assets/fontawesome/webfonts/fa-brands-400.woff2
  assets/fontawesome/webfonts/fa-regular-400.eot
  assets/fontawesome/webfonts/fa-regular-400.svg
  assets/fontawesome/webfonts/fa-regular-400.ttf
  assets/fontawesome/webfonts/fa-regular-400.woff
  assets/fontawesome/webfonts/fa-regular-400.woff2
  assets/fontawesome/webfonts/fa-solid-900.eot
  assets/fontawesome/webfonts/fa-solid-900.svg
  assets/fontawesome/webfonts/fa-solid-900.ttf
  assets/fontawesome/webfonts/fa-solid-900.woff
  assets/fontawesome/webfonts/fa-solid-900.woff2
  assets/js/sections/flightpath.js
  assets/js/sections/satellite_functions.js
  assets/js/sections/satpasses.js
  src/predict/Predict.php
Labels: frontend, new feature

#1781 Fence for spaces at call
  application/controllers/User.php
  application/models/Logbook_model.php
  application/models/Stations.php
  application/views/station_profile/edit.php
  application/views/user/edit.php
  application/views/user/modals/first_login_wizard.php
Labels: fence

#1780 Use last worked sat for preset of flightpath selected satellite
  application/controllers/Satellite.php
  application/models/Satellite_model.php
  application/views/satellite/flightpath.php
Labels: frontend

#1787 Check key before doing huge SQLs
  application/controllers/Api.php
Labels: security

#1779 Add display of hams of note
  application/config/migration.php
  application/controllers/Debug.php
  application/controllers/Lookup.php
  application/controllers/Update.php
  application/migrations/239_add_hams_of_note.php
  application/models/Pota.php
  application/models/Update_model.php
  application/views/debug/index.php
  application/views/qso/index.php
  application/views/update/hamsofnote.php
  assets/js/sections/qso.js
Labels: enhancement, frontend

#1794 Show pass as polar view
  application/views/satellite/passtable.php
Labels: enhancement, frontend

#1799 two informations for max-ele-arrow:
  application/views/satellite/passtable.php
Labels: enhancement

#1806 Use stars to hide QRZ-Key and add "eye"-button
  application/views/station_profile/edit.php
  assets/js/sections/station_locations.js
Labels: frontend

#1813 Added AOS and LOS to MapView/Info
  assets/js/sections/flightpath.js
Labels: enhancement, frontend

#1814 Make Hams Of Note configurable at Adminmenu
  application/controllers/Options.php
  application/models/Pota.php
  application/models/Update_model.php
  application/views/options/hon.php
  application/views/options/sidebar.php
Labels: enhancement

#1804 Autofill az ele qso
  application/controllers/Qso.php
  application/views/interface_assets/footer.php
  application/views/qso/index.php
  application/views/qso/log_qso.php
  assets/js/sections/qso.js
Labels: enhancement

#1816 Hint for missing locations at quick-switcher
  application/views/interface_assets/header.php
Labels: frontend

#1818 Handle cases of no AOS/LOS
  assets/js/sections/flightpath.js
Labels: bug

#1821 (Re-)calculate distance upon updating QSOs from callbook within LBA
  application/controllers/Logbookadvanced.php
  application/models/Logbookadvanced_model.php
Labels: frontend

#1822 Fix an issue where qsl_sent wasn't set
  application/models/Logbook_model.php
  assets/js/sections/common.js
Labels: bug, frontend
