Repository wavelog/wavelog, pull requests merged in 2025-08, with the labels that each got.

#2209 Fix admin
  application/controllers/User.php
Labels: bug

#2220 Added RST to LBA
  application/models/Logbookadvanced_model.php
  application/views/logbookadvanced/edit.php
  assets/js/sections/logbookadvanced_edit.js
Labels: enhancement

#2233 Show Mode in DXCluster (preparation for passing it to the gate)
  application/models/Dxcluster_model.php
  application/views/bandmap/list.php
  assets/js/sections/bandmap_list.js
Labels: enhancement

#2239 Change default RST on fav selection
  assets/js/sections/qso.js
Labels: bug, enhancement, frontend

#2249 Map T2 sat names for amsat status upload
  application/models/Logbook_model.php
Labels: enhancement

#2248 Show confirmation-Method at DXCC Award instead of simple "C"
  application/models/Dxcc.php
  application/views/awards/dxcc/index.php
Labels: frontend, new feature
